apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret-otel
  namespace: o11y-otel
type: Opaque
data:
  elastic_api_key: <UPDATE THIS>
  elastic_endpoint: <elastic-endpoint>
  data_stream_namespace: <datastream-namespace>
  eh_endpoint: <eventhub-endpoint>
  eh_shared_access_keyname: <UPDATE THIS>
  eh_shared_access_key: <UPDATE THIS>
  subscription_id: <azure-subscription-id>
  resource_group: <az-resource-group>
  azure_client_id: <UPDATE THIS>
  azure_tenant_id: <az-tenant-id>
