apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-otc-eventhub-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
