apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-storage-elasticapm-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-storage-secret  # Contains storage account name + key
    shareName: elasticapm-data
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
